---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "livepeer/go-livepeer:{{ .Values.orchestrator.version }}"
          command: ["/usr/local/bin/livepeer"]
          args:
            - -v=6
            - -network={{ .Values.orchestrator.network }}
            - -orchestrator=true
            - -transcoder=true
            - -monitor=true
            - -cliAddr=0.0.0.0:7935
            - -httpAddr=0.0.0.0:8935
            - -serviceAddr={{ .Values.global.domain }}:8935
            - -maxSessions={{ get .Values.orchestrator.maxSessionsPerOrchestratorForRegion .Values.global.geolocation }}
            - -nvidia=all
            - -ethUrl=http://arbitrum-nginx-proxy:8555
            {{- if not .Values.orchestrator.reward }}
            - -reward=false
            {{- end }}
            - -ethPassword=$(ETH_PASSWORD)
            - -ethOrchAddr={{ .Values.orchestrator.ethAddress }}
            - -pricePerUnit={{ .Values.orchestrator.pricePerUnit }}
            - -autoAdjustPrice=false
            - -blockPollingInterval={{ .Values.orchestrator.blockPollingInterval }}
            - -maxFaceValue={{ .Values.orchestrator.maxFaceValue }}
          env:
            - name: ETH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: json-key-password
                  key: json-key-password
          ports:
            - name: https
              containerPort: 8935
            - name: cli
              containerPort: 7935
          resources:
            requests:
              memory: 1Gi
              cpu: '1000m'
              nvidia.com/gpu: 1
            limits:
              memory: 4Gi
              cpu: '2000m'
              nvidia.com/gpu: 1
          livenessProbe:
            httpGet:
              path: /status
              port: cli
          volumeMounts:
            - name: lp-data
              mountPath: /root/.lpData
            - name: json-private-key
              mountPath: "/root/.lpData/{{ .Values.orchestrator.network }}/keystore/wallet"
              subPath: key.json
              readOnly: true
        - name: "{{ .Chart.Name }}-gpu-monitoring"
          image: "0xcadams/nvidia-gpu-monitoring@sha256:cffb30fbf711f88042fcdf5b030f2b81ee1ec7209493a569de253dfeaac19227"
          env:
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,video,utility
          ports:
            - name: gpu-metrics
              containerPort: 9102
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: json-private-key
          secret:
            secretName: json-private-key
            defaultMode: 0400
        - name: lp-data
          emptyDir:
            medium: Memory
