---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Chart.Name }}-monitor"
  labels:
    release: "global"
    version: "{{ .Values.global.releaseVersion }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  endpoints:
    - port: cli
      path: "/metrics"
    - port: gpu-metrics
      path: "/metrics/"

