---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Chart.Name }}-monitor"
  labels:
    release: "global"
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  endpoints:
    - port: cli
      path: "/metrics"
  targetLabels:
    - "{{ .Values.orchestrator.region }}"
