---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: https
      port: 8935
      targetPort: https
    - name: cli
      port: 7935
      targetPort: cli
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
