---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "offchainlabs/arb-node:{{ .Values.arbitrum.version }}"
          args: ["--l1.url http://geth:8545"]
          ports:
            - name: rpc
              containerPort: 8547
            - name: ws
              containerPort: 8548
            - name: seq
              containerPort: 9642
          volumeMounts:
            - name: arb-datadir
              mountPath: /home/user/.arbitrum/mainnet
      volumes:
        - name: arb-datadir
          emptyDir: {}
