---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx-proxy
  labels:
    app: {{ .Chart.Name }}-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-nginx-proxy
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-nginx-proxy
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx-proxy
          image: nginx:latest
          ports:
            - name: rpc
              containerPort: 8555
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Chart.Name }}-nginx-proxy
        - name: log
          emptyDir: {}
