---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx-proxy
  labels:
    app: {{ .Chart.Name }}-nginx-proxy
spec:
  ports:
    - port: 8555
      targetPort: rpc
  selector:
    app: {{ .Chart.Name }}-nginx-proxy
  type: ClusterIP
