---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-nginx-proxy"
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
      worker_connections 10240;
    }

    http {
      server {
        listen 0.0.0.0:8555;

        location / {
          proxy_set_header Authorization "Basic {{ (printf "%s:%s" .Values.arbitrum.rpc.username .Values.arbitrum.rpc.password) | b64enc }}";
          proxy_pass https://rpc.{{ .Values.global.domain }};
        }
      }
    }
