---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-failover
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;

    events {
      worker_connections 10240;
    }

    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log	/var/log/nginx/access.log main;

      upstream rpc {
        server {{ .Chart.Name }}:8547 max_fails=1 fail_timeout=3s;

        server 0.0.0.0:8556 backup;
      }

      server {
        listen 0.0.0.0:8556;
        location / {
          proxy_pass https://arbitrum-mainnet.infura.io/v3/{{ .Values.arbitrum.infuraProjectId }};
        }
      }

      server {
        listen 0.0.0.0:8555;

        location / {
          proxy_pass http://rpc;
        }
      }
    }
