{{ if .Values.global.isPrimaryCluster }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-failover
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
      worker_connections 10240;
    }

    http {
      upstream rpc1 {
        server {{ .Chart.Name }}:8547 max_fails=1 fail_timeout=3s;

        server 0.0.0.0:8556 backup;
      }

      server {
        listen 0.0.0.0:8556;
        location / {
          proxy_pass http://rpc2;
        }
      }

      upstream rpc2 {
        server 0.0.0.0:8557;

        server 0.0.0.0:8558 backup;
      }

      server {
        listen 0.0.0.0:8557;
        location / {
          proxy_pass https://rpc.ftklivepeer.net/api/{{ .Values.arbitrum.ftkuhnsmanApiKey }}/l2/;
          proxy_set_header Host rpc.ftklivepeer.net;
          proxy_set_header X-Forwarded-Host rpc.ftklivepeer.net;
        }
      }

      server {
        listen 0.0.0.0:8558;
        location / {
          proxy_pass https://arbitrum-mainnet.infura.io/v3/{{ .Values.arbitrum.infuraProjectId }};
          proxy_set_header Host arbitrum-mainnet.infura.io;
          proxy_set_header X-Forwarded-Host arbitrum-mainnet.infura.io;
        }
      }

      server {
        listen 0.0.0.0:8555;

        location / {
          proxy_pass http://rpc2;
        }
      }
    }
{{ end }}
