---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "{{ projectName }}"
  region: "{{ region }}"

managedNodeGroups:
  - name: "nvidia-1"
    instanceType: "g4dn.xlarge"
    desiredCapacity: 1
    volumeSize: 80
    labels:
      nvidia: "true"
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: "general-1"
    instanceType: "t3.small"
    desiredCapacity: {{ generalPodCapacity }}
    volumeSize: 80
    labels:
      nvidia: "false"
    iam:
      withAddonPolicies:
        autoScaler: true
