---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "{{ projectName }}-{{ region }}"
  region: "{{ region }}"

managedNodeGroups:
  - name: "nvidia-1"
    instanceType: "t4g.medium" # "g4dn.xlarge"
    desiredCapacity: 1
    volumeSize: 100
