apiVersion: skaffold/v2beta21
kind: Config

deploy:
  helm:
    releases:
      - name: geth
        createNamespace: true
        chartPath: charts/geth
        setValueTemplates:
          global.isPrimaryCluster: "{{.IS_PRIMARY_CLUSTER}}"
          global.releaseVersion: "{{.RELEASE_VERSION}}"
          global.projectName: "{{.PROJECT_NAME}}"
          global.region: "{{.AWS_REGION}}"
          global.domain: "{{.DOMAIN}}"
          geth.version: "{{.GETH_VERSION}}"
          geth.region: "{{.AWS_REGION}}"
      - name: arbitrum
        createNamespace: true
        chartPath: charts/arbitrum
        setValueTemplates:
          global.isPrimaryCluster: "{{.IS_PRIMARY_CLUSTER}}"
          global.releaseVersion: "{{.RELEASE_VERSION}}"
          global.projectName: "{{.PROJECT_NAME}}"
          global.region: "{{.AWS_REGION}}"
          global.domain: "{{.DOMAIN}}"
          arbitrum.version: "{{.ARBITRUM_VERSION}}"
          arbitrum.infuraProjectId: "{{.INFURA_PROJECT_ID}}"
          arbitrum.ftkuhnsmanApiKey: "{{.FTKUHNSMAN_API_KEY}}"
          arbitrum.rpc.username: "{{.RPC_BASIC_AUTH_USERNAME}}"
          arbitrum.rpc.password: "{{.RPC_BASIC_AUTH_PASSWORD}}"
      - name: global
        createNamespace: true
        chartPath: charts/global
        setValueTemplates:
          global.isPrimaryCluster: "{{.IS_PRIMARY_CLUSTER}}"
          global.releaseVersion: "{{.RELEASE_VERSION}}"
          global.projectName: "{{.PROJECT_NAME}}"
          global.region: "{{.AWS_REGION}}"
          global.domain: "{{.DOMAIN}}"
          external-dns.txtPrefix: "{{.AWS_REGION}}."
          external-dns.txtOwnerId: "{{.PROJECT_NAME}}"
          letsencrypt.email: "{{.SUPPORT_EMAIL}}"
          prometheus-json-exporter.serviceMonitor.targets[0].url: "https://leaderboard-serverless.vercel.app/api/aggregated_stats?orchestrator={{.ETH_ADDRESS}}"
          kube-prometheus-stack.prometheus.prometheusSpec.externalLabels.region: "{{.AWS_REGION}}"
          kube-prometheus-stack.prometheus.prometheusSpec.externalLabels.version: "{{.RELEASE_VERSION}}"
          kube-prometheus-stack.grafana.enabled: "{{.IS_PRIMARY_CLUSTER}}"
          kube-prometheus-stack.grafana.adminPassword: "{{.GRAFANA_PASSWORD}}"
          thanos.query.enabled: "{{.IS_PRIMARY_CLUSTER}}"
          thanos.queryFrontend.enabled: "{{.IS_PRIMARY_CLUSTER}}"
          thanos.compactor.enabled: "{{.IS_PRIMARY_CLUSTER}}"
          thanos.storegateway.enabled: "{{.IS_PRIMARY_CLUSTER}}"
      - name: orchestrator
        createNamespace: true
        chartPath: charts/orchestrator
        setValueTemplates:
          global.isPrimaryCluster: "{{.IS_PRIMARY_CLUSTER}}"
          global.releaseVersion: "{{.RELEASE_VERSION}}"
          global.projectName: "{{.PROJECT_NAME}}"
          global.region: "{{.AWS_REGION}}"
          global.domain: "{{.DOMAIN}}"
          orchestrator.ethAddress: "{{.ETH_ADDRESS}}"
          orchestrator.version: "{{.LIVEPEER_VERSION}}"
          orchestrator.pricePerUnit: "{{.PRICE_PER_UNIT}}"
          orchestrator.reward: "{{.REWARD}}"
          orchestrator.jsonWalletPassword: "{{.JSON_WALLET_PASSWORD}}"
