apiVersion: skaffold/v2beta21
kind: Config

deploy:
  helm:
    releases:
      - name: global
        createNamespace: true
        chartPath: charts/global
        setValueTemplates:
          letsencrypt.email: "{{.SUPPORT_EMAIL}}"
          external-dns.txt-owner-id: "{{.ROUTE_53_HOSTED_ZONE_ID}}"
      - name: geth
        createNamespace: true
        chartPath: charts/geth
        setValueTemplates:
          geth.version: "{{.GETH_VERSION}}"
      - name: arbitrum
        createNamespace: true
        chartPath: charts/arbitrum
        setValueTemplates:
          arbitrum.version: "{{.ARBITRUM_VERSION}}"
          arbitrum.infuraProjectId: "{{.INFURA_PROJECT_ID}}"
      - name: orchestrator
        createNamespace: true
        chartPath: charts/orchestrator
        setValueTemplates:
          region: "{{.AWS_REGION}}"
          domain: "{{.DOMAIN}}"
          orchestrator.version: "{{.LIVEPEER_VERSION}}"
          orchestrator.pricePerUnit: "{{.PRICE_PER_UNIT}}"
          orchestrator.reward: "{{.REWARD}}"
          orchestrator.jsonKey: "{{.JSON_KEY}}"
          orchestrator.jsonKeyPassword: "{{.JSON_KEY_PASSWORD}}"
