---
global:
  isPrimaryCluster: false
  releaseVersion: changeme
  projectName: changeme
  domain: changeme
  region: changeme

tester:
  schedule: "*/5 * * * *"
  network: arbitrum-one-mainnet
  ethAddress: 0xchangeme

  version: "latest"

  maxTicketEV: "100000000000000"
  maxPricePerUnit: "100000"
