---
kind: Secret
apiVersion: v1
metadata:
  name: aws-iam-credentials
type: Opaque
data:
  aws-access-key-id: "{{ .Values.global.awsAccessKeyId | b64enc }}"
  aws-secret-access-key: "{{ .Values.global.awsSecretAccessKey | b64enc }}"
