---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: 'letsencrypt-cluster-issuer'
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
spec:
  acme:
    server: '{{ .Values.letsencrypt.api }}'
    email: '{{ .Values.letsencrypt.email }}'
    privateKeySecretRef:
      name: 'letsencrypt-issuer'
    solvers:
      - selector:
          dnsZones:
            - "{{ $.Values.global.domain }}"
        dns01:
          route53:
            region: us-east-1
