{{ if .Values.global.isPrimaryCluster }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls:
    - hosts:
        - "grafana.{{ .Values.global.domain }}"
      secretName: "{{ .Chart.Name }}-ingress-tls-secret"
  ingressClassName: nginx
  rules:
    - host: "grafana.{{ .Values.global.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}-grafana"
                port:
                  number: 3000
{{ end }}
