---
kind: Secret
apiVersion: v1
metadata:
  name: json-key-password
type: Opaque
data:
  json-key-password: "{{ .Values.global.primaryJsonWalletPassword | b64enc }}"
  # {{- if .Values.global.isPrimaryCluster }}
  # {{- else }}
  # json-key-password: "{{ .Values.global.secondaryJsonWalletPassword | b64enc }}"
  # {{- end }}
