---
kind: Secret
apiVersion: v1
metadata:
  name: json-private-key-password
type: Opaque
data:
  {{- if .Values.global.isPrimaryCluster }}
  json-private-key-password: "{{ .Values.global.primaryJsonWalletPassword | b64enc }}"
  {{- else }}
  json-private-key-password: "{{ .Values.global.secondaryJsonWalletPassword | b64enc }}"
  {{- end }}
