# this service handles the deployment of the global DNS entries
# which route requests based on latency to a region
{{ if .Values.global.isPrimaryCluster }}
{{- range $key, $val := .Values.global.geolocationAwsRegions }}
---
kind: Service
apiVersion: v1
metadata:
  name: "{{ $.Chart.Name }}-{{ $key }}-regional-service"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.global.domain }}"
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $key }}-id"
    external-dns.alpha.kubernetes.io/aws-region: "{{ $val }}"
spec:
  type: ExternalName
  externalName: "{{ $key }}.{{ $.Values.global.domain }}"
{{- end }}
{{ end }}
