{{ if .Values.global.isMainRegion }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-config
type: Opaque
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: {{ .Values.global.projectName }}
      endpoint: s3.{{ .Values.global.region }}.amazonaws.com
      aws_sdk_auth: true
{{ end }}
