---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-config
type: Opaque
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: {{ .Values.global.projectName }}
      endpoint: s3.us-east-1.amazonaws.com
      access_key: "{{ .Values.global.awsAccessKeyId }}"
      secret_key: "{{ .Values.global.awsSecretAccessKey }}"
