{{ if .Values.global.isPrimaryCluster }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-thanos-sd"
data:
  servicediscovery.yml: |
    - targets:
      {{- range .Values.global.allRegions }}
      - 'https://{{ . }}.thanos.{{ $.Values.global.domain }}'
      {{- end }}
{{ end }}
