{
 "title": "Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; margin-top: 15px\"><h2>open-orchestrator.eth</h2>\n\n<h5>Globally distributed, high-performance, and <a href=\"https://github.com/0xcadams/livepeer-open-orchestrator\">open-source</a> orchestrator operated by a protocol engineer @ Livepeer.</h5>\n</div>"
   }
  },
  {
   "title": "Tickets Received (Past Day)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(geolocation) (increase(livepeer_tickets_recv[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orchestrator Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(geolocation) (livepeer_current_sessions_total{node_type=\"orch\"}) / sum by(geolocation) (livepeer_max_sessions_total{node_type=\"orch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expected ETH Payout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Ξ" } },
   "targets": [
    {
     "expr": "(sum(livepeer_ticket_value_recv)-(sum(livepeer_value_redeemed) OR on() vector(0)))/10^9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Projected Income",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_ticket_value_recv[1d])*60*60*24)/10^9"
    }
   ]
  },
  {
   "title": "Node Stats",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(geolocation) (livepeer_current_sessions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Success Rate",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(source) (transcoding_stream_scores_success_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Latency",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "1 - 2.71828^-(avg by(source) (transcoding_stream_scores_seg_duration) / avg by(source) (transcoding_stream_scores_round_trip_time))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transcode Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(profiles) (rate(livepeer_transcode_time_seconds_sum[1m])) / avg by(profiles) (rate(livepeer_transcode_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transcode Scores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg by(profiles) (rate(livepeer_transcode_score_sum[1m])) / avg by(profiles) (rate(livepeer_transcode_score_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Egress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(host) (rate(nginx_ingress_controller_bytes_sent_sum{host!=\"_\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(host) (rate(nginx_ingress_controller_requests{status!=\"200\", host!=\"_\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Orchestrator Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sum(livepeer_versions{})" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(sum by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg by(geolocation) (temperature_gpu * 9 / 5 + 32)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "avg(livepeer_suggested_gas_price)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}