---
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.8.0
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 6.4.4
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.1.1
  - name: nvidia-device-plugin
    repository: https://nvidia.github.io/k8s-device-plugin
    version: v0.11.0
