---
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.8.0
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns
    version: 1.9.0
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.1.1
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 35.5.1
  - name: prometheus-json-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 0.2.1
    condition: prometheus-json-exporter.enabled
  - name: thanos
    repository: https://charts.bitnami.com/bitnami
    version: 10.5.0
  - name: nvidia-device-plugin
    repository: https://nvidia.github.io/k8s-device-plugin
    version: 0.12.0
    condition: nvidia-device-plugin.enabled
