---
cert-manager:
  installCRDs: true
  nodeSelector:
    beta.kubernetes.io/os: linux # to avoid scheduling on windows VMs

external-dns:
  policy: sync
  provider: aws
  aws-zone-type: public
  registry: txt
  txt-owner-id: changeme

letsencrypt:
  email: me@changeme.com
  api: https://acme-v02.api.letsencrypt.org/directory

ingress-nginx:
  controller:
    replicaCount: 1
    config:
      proxy-body-size: "0"
      hsts-preload: "true"
