---
cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

global:
  isMainRegion: false
  domain: changeme
  region: changeme
  allRegions:
    - "us-east-1"
    - "ap-southeast-1"

letsencrypt:
  email: me@changeme.com
  api: https://acme-v02.api.letsencrypt.org/directory

external-dns:
  policy: sync
  provider: aws
  txtOwnerId: changeme
  txtPrefix: changeme

ingress-nginx:
  controller:
    replicaCount: 1
    config:
      proxy-body-size: "0"
      hsts-preload: "true"

prometheus-node-exporter:
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
