---
cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      labels:
        release: "global"

global:
  projectName: changeme
  isMainRegion: false
  domain: changeme
  region: changeme
  allRegions:
    - "us-east-1"
    - "eu-central-1"

letsencrypt:
  email: me@changeme.com
  api: https://acme-v02.api.letsencrypt.org/directory

external-dns:
  policy: sync
  provider: aws
  txtOwnerId: changeme
  txtPrefix: changeme

kube-prometheus-stack:
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      thanos:
        objectStorageConfig:
          key: "objstore.yml"
          name: "thanos-config"
      externalLabels:
        region: changeme
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true

thanos:
  existingObjstoreSecret: "thanos-config"
  query:
    enabled: false
    dnsDiscovery:
      sidecarsService: "global-kube-prometheus-sta-thanos-discovery"
  queryFrontend:
    enabled: false
  compactor:
    enabled: false
  storegateway:
    enabled: false
  ruler:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ingress-nginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: global
        enabled: true
    replicaCount: 1
    config:
      proxy-body-size: "0"
      hsts-preload: "true"
