---
cert-manager:
  installCRDs: true
  nodeSelector:
    beta.kubernetes.io/os: linux # to avoid scheduling on windows VMs

external-dns:
  policy: upsert-only # this must be upsert only, since multiple regions are editing the same dns
  provider: aws
  aws-zone-type: public
  registry: txt
  txtOwnerId: changeme

ingress-nginx:
  controller:
    replicaCount: 1
    config:
      proxy-body-size: "0"
      hsts-preload: "true"
