---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  ports:
    - name: cli
      port: 7935
      targetPort: cli
    - name: graph-http
      port: 7402
      targetPort: graph-http
  selector:
    app: "{{ .Chart.Name }}"
  type: ClusterIP
