apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  schedule: "{{ .Values.tester.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: "{{ .Chart.Name }}"
              image: "livepeer/orch-tester:{{ .Values.tester.version }}"
              env:
                - name: OT_ETHPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: json-key-password
                      key: json-key-password
                - name: OT_REGION
                  value: "{{ .Values.global.region }}"
                - name: OT_SUBGRAPH
                  value: "http://{{ .Chart.Name }}:7402"
                - name: OT_LEADERBOARD
                  value: "http://{{ .Chart.Name }}:7402"
                - name: OT_LEADERBOARD_SECRET
                  value: ""
                - name: OT_PROFILES
                  value: "3"
                - name: OT_PRESETS
                  value: "P240p30fps16x9,P360p30fps16x9,P720p30fps16x9"
                - name: OT_VIDEO
                  value: "official_test_source_2s_keys_24pfs_30s_hls/bbb.m3u8"
                - name: OT_NETWORK
                  value: "{{ .Values.tester.network }}"
                - name: OT_ETHURL
                  value: "http://arbitrum-nginx-proxy:8555"
                - name: OT_MAXTICKETEV
                  value: "{{ .Values.tester.maxTicketEV }}"
                - name: OT_MAXPRICEPERUNIT
                  value: "{{ .Values.tester.maxPricePerUnit }}"
              resources:
                limits:
                  cpu: 250m
                  memory: 500Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              livenessProbe:
                httpGet:
                  path: /status
                  port: cli
              volumeMounts:
                - name: "{{ .Chart.Name }}-lp-data"
                  mountPath: /root/.lpData
                - name: "{{ .Chart.Name }}-json-private-key"
                  mountPath: "/root/.lpData/{{ .Values.tester.network }}/keystore/wallet"
                  subPath: key.json
                  readOnly: true
            - name: "{{ .Chart.Name }}-single-orchestrator-subgraph"
              image: "0xcadams/single-orchestrator-subgraph:latest"
              env:
                - name: TRANSCODER_ID
                  value: "{{ .Values.tester.ethAddress }}"
                - name: TRANSCODER_SERVICE_URI
                  value: "{{ .Values.global.domain }}:8935"
              ports:
                - name: graph-http
                  containerPort: 7402
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 50Mi
          volumes:
            - name: "{{ .Chart.Name }}-json-private-key"
              secret:
                secretName: json-private-key
                defaultMode: 0400
            - name: "{{ .Chart.Name }}-lp-data"
              emptyDir:
                medium: Memory
