---
orchestrator:
  replicaCount: 1
  network: offchain # arbitrum-one-mainnet
  ethAddress: 0xchangeme

  version: changeme
  pricePerUnit: 1100
  blockPollingInterval: 10
  reward: 'false'

  jsonWalletPassword: changeme

  region: changeme
  domain: changeme.com
