---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "ethereum/client-go:{{ .Values.geth.version }}"
          command: ["/bin/sh", "-c", "geth --cache 256 --maxpeers 50 --syncmode light --http --http.vhosts '*' --http.corsdomain '*' --http.api eth,web3,debug,txpool,net,admin,debug --ws --ws.api eth,web3,debug,txpool,net,admin,debug --ws.origins '*'"]
          ports:
            - name: rpc
              containerPort: 8545
            - name: ws
              containerPort: 8546
            - name: p2p
              containerPort: 30303
            - name: p2p-udp
              containerPort: 30303
              protocol: UDP
          resources:
            requests:
              memory: 2G
              cpu: 600m
            limits:
              memory: 4G
              cpu: 1500m
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          volumeMounts:
            - name: geth-datadir
              mountPath: /opt/geth/geth
      volumes:
        - name: geth-datadir
          emptyDir: {}
