{{ if .Values.global.isPrimaryCluster }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: alpha.eksctl.io/nodegroup-name
                    operator: In
                    values:
                      - large-4
      containers:
        - name: "{{ .Chart.Name }}"
          image: "ethereum/client-go:{{ .Values.geth.version }}"
          command: ["/bin/sh", "-c", "geth --cache 2048 --metrics --metrics.addr 0.0.0.0 --http --http.addr '0.0.0.0' --http.vhosts '*' --http.corsdomain '*' --http.api eth,web3,debug,txpool,net,admin,debug --ws --ws.api eth,web3,debug,txpool,net,admin,debug --ws.origins '*'"]
          ports:
            - name: rpc
              containerPort: 8545
            - name: ws
              containerPort: 8546
            - name: metrics
              containerPort: 6060
            - name: p2p
              containerPort: 30303
            - name: p2p-udp
              containerPort: 30303
              protocol: UDP
          resources:
            requests:
              memory: 4G
              cpu: '2500m'
            limits:
              memory: 8G
              cpu: '4000m'
          # readinessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - '[ "`geth attach --exec "eth.syncing"`" = "false" ]'
          #   initialDelaySeconds: 360
          #   periodSeconds: 30
          #   failureThreshold: 1000
          volumeMounts:
            - name: geth-datadir
              mountPath: /root
  serviceName: "{{ .Chart.Name }}"
  podManagementPolicy: Parallel
  volumeClaimTemplates:
    - metadata:
        name: geth-datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1000Gi
{{ end }}
