---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  ports:
    - port: 8545
      targetPort: rpc
    - port: 8546
      targetPort: ws
    - port: 30303
      targetPort: p2p
    - port: 30303
      targetPort: p2p-udp
      protocol: UDP
  selector:
    app: "{{ .Chart.Name }}"
  type: ClusterIP
