name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Kubernetes"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install
        run: yarn --immutable

      - uses: azure/setup-helm@v2.1
      - uses: azure/setup-kubectl@v2.1
        with:
          version: "v1.23.6"

      - name: Deploy with Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

          yarn deploy:eks:virginia
        env:
          PROJECT_NAME: "livepeer-open-orchestrator"
          IS_PRIMARY_CLUSTER: "false"
          PRICE_PER_UNIT: "1100"

          LIVEPEER_VERSION: "0.5.31-3aa5ee0d"
          GETH_VERSION: "v1.10.18"
          ARBITRUM_VERSION: "v1.4.0-f4bbe91"

          RPC_BASIC_AUTH_USERNAME: "orchestrator"

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          DOMAIN: ${{ secrets.DOMAIN }}
          SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
          ETH_ADDRESS: ${{ secrets.ETH_ADDRESS }}

          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          FTKUHNSMAN_API_KEY: ${{ secrets.FTKUHNSMAN_API_KEY }}

          RPC_BASIC_AUTH_PASSWORD: ${{ secrets.RPC_BASIC_AUTH_PASSWORD }}
