name: deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: "Deploy to Kubernetes"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install
        run: yarn --immutable

      - uses: azure/setup-helm@v2.1
      - uses: azure/setup-kubectl@v3.0

      - name: Get Release Version
        id: tag_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}

      - name: Deploy with Skaffold
        run: |
          export KUBECONFIG="${KUBECONFIG}:./kube-config-california"
          echo $KUBE_CONFIG_CALIFORNIA_B64 | base64 -d > ./kube-config-california

          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

          helm repo add cert-manager https://charts.jetstack.io
          helm repo add external-dns https://kubernetes-sigs.github.io/external-dns
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
          helm repo add thanos https://charts.bitnami.com/bitnami
          helm repo add nvidia-device-plugin https://nvidia.github.io/k8s-device-plugin

          yarn deploy:virginia
          yarn deploy:frankfurt
          yarn deploy:california
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          NODE_AWS_ACCESS_KEY_ID: ${{ secrets.NODE_AWS_ACCESS_KEY_ID }}
          NODE_AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_AWS_SECRET_ACCESS_KEY }}

          KUBE_CONFIG_CALIFORNIA_B64: ${{ secrets.KUBE_CONFIG_CALIFORNIA_B64 }}

          PROJECT_NAME: "livepeer-open-orchestrator"
          PRICE_PER_UNIT: "1198"

          RELEASE_VERSION: ${{ steps.tag_version.outputs.RELEASE_VERSION }}

          RPC_BASIC_AUTH_USERNAME: "orchestrator"
          RPC_BASIC_AUTH_PASSWORD: ${{ secrets.RPC_BASIC_AUTH_PASSWORD }}

          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

          DOMAIN: ${{ secrets.DOMAIN }}
          SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}

          ETH_ADDRESS: ${{ secrets.ETH_ADDRESS }}
          PRIMARY_JSON_WALLET_PASSWORD: ${{ secrets.PRIMARY_JSON_WALLET_PASSWORD }}
          SECONDARY_JSON_WALLET_PASSWORD: ${{ secrets.SECONDARY_JSON_WALLET_PASSWORD }}

          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          FTKUHNSMAN_API_KEY: ${{ secrets.FTKUHNSMAN_API_KEY }}
