name: docker

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: "Push to Docker"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Release Version
        id: tag_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push GPU monitoring
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/nvidia-gpu-monitoring"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 0xcadams/nvidia-gpu-monitoring:latest,0xcadams/nvidia-gpu-monitoring:${{ steps.tag_version.outputs.RELEASE_VERSION }}
      - name: Build and push orchestrator tester
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/single-orchestrator-subgraph"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 0xcadams/single-orchestrator-subgraph:latest,0xcadams/single-orchestrator-subgraph:${{ steps.tag_version.outputs.RELEASE_VERSION }}
